spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://
  jpa:
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
    show-sql: true
razorpay:
  api:
    key: rzp_test_T1aPDxOy22KIol
    secret: zdQFFvVQPfsfj3wrTRO3iyOs
