export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const FIND_ORDERS_REQUEST = "FIND_ORDERS_REQUEST";
export const FIND_ORDERS_SUCCESS = "FIND_ORDERS_SUCCESS";
export const FIND_ORDERS_FAILURE = "FIND_ORDERS_FAILURE";

export const FIND_ORDER_BY_ID_REQUEST = "FIND_ORDER_BY_ID_REQUEST";
export const FIND_ORDER_BY_ID_SUCCESS = "FIND_ORDER_BY_ID_SUCCESS";
export const FIND_ORDER_BY_ID_FAILURE = "FIND_ORDER_BY_ID_FAILURE";

export const FIND_USER_ADDRESSES_REQUEST = "FIND_USER_ADDRESSES_REQUEST";
export const FIND_USER_ADDRESSES_SUCCESS = "FIND_USER_ADDRESSES_SUCCESS";
export const FIND_USER_ADDRESSES_FAILURE = "FIND_USER_ADDRESSES_FAILURE";

export const CREATE_PAYMENT_REQUEST = "CREATE_PAYMENT_REQUEST";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_FAILURE = "CREATE_PAYMENT_FAILURE";

export const UPDATE_PAYMENT_REQUEST = "UPDATE_PAYMENT_REQUEST";
export const UPDATE_PAYMENT_SUCCESS = "UPDATE_PAYMENT_SUCCESS";
export const UPDATE_PAYMENT_FAILURE = "UPDATE_PAYMENT_FAILURE";

export const CLEAR_ORDER_ERROR = "CLEAR_ORDER_ERROR";
